import { FinanceRepository } from './store.js';
import { amortize, budgetProgress, cashFlow, decimal, financialPeriod, goalProjection, investmentGain, money, netWorth, ratio, reportingMonthOffset } from './domain.js';
import { parseBankingSms } from './sms-parser.js';

const repo = new FinanceRepository();
let data;
try { data = await repo.initialize(true); }
catch (error) { document.querySelector('#app').innerHTML = `<main class="login"><section class="card login-card"><div class="brand"><img class="brand-mark" src="./assets/quiet-ledger-icon.svg" alt="">Quiet Ledger</div><h1>Database unavailable</h1><p class="muted">${String(error.message).replace(/[&<>'"]/g,'')}</p><p class="small muted">Start MySQL and the Spring Boot server, then refresh this page.</p></section></main>`; throw error; }
let search = '';
let selectedMonth = sessionStorage.getItem('harbor-finance-period') || new Date().toISOString().slice(0, 7);
const sortState = { transactions:{ key:'date', direction:'desc' }, investments:{ key:'name', direction:'asc' }, accounts:{ key:'name', direction:'asc' }, bills:{ key:'dueDate', direction:'asc' }, goals:{ key:'priority', direction:'asc' }, loans:{ key:'name', direction:'asc' } };
const routes = [
  ['overview','Overview','⌂'],['accounts','Accounts','▣'],['transactions','Transactions','⇄'],['budget','Budget','◫'],['bills','Bills','▤'],['goals','Goals','◎'],['investments','Investments','↗'],['net-worth','Net Worth','◇'],['reports','Reports','▥'],['calendar','Calendar','□'],['loans','Loans','⌁'],['settings','Settings','⚙']
];
const app = document.querySelector('#app');
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
const get = (resource, id) => data[resource]?.find((item) => item.id === id);
const fmt = (minor, currency = data.settings.primaryCurrency) => new Intl.NumberFormat(data.settings.locale, { style:'currency', currency, maximumFractionDigits: 0 }).format(Number(minor) / 100);
const amt = (value, currency) => fmt(money(value), currency);
const pct = (basisPoints) => `${(Number(basisPoints) / 100).toFixed(1)}%`;
const title = (route) => routes.find(([key]) => key === route)?.[1] || (route === 'assistant' ? 'AI Assistant' : 'Overview');
const route = () => location.hash.replace(/^#\/?/, '').split('?')[0] || 'overview';
const periodBounds = () => financialPeriod(selectedMonth, data.settings.monthStart);
const inPeriod = (record, dateField = 'date') => { const date=String(record[dateField] || '').slice(0,10),bounds=periodBounds(); return date >= bounds.from && date <= bounds.to; };
const periodTransactions = () => data.transactions.filter((transaction) => inPeriod(transaction));
const periodLabel = () => new Intl.DateTimeFormat(data.settings.locale, { month:'long', year:'numeric', timeZone:'UTC' }).format(new Date(`${selectedMonth}-01T12:00:00Z`));
const monthLabel = (month) => new Intl.DateTimeFormat(data.settings.locale, { month:'long', year:'numeric', timeZone:'UTC' }).format(new Date(`${month}-01T12:00:00Z`));
const periodRangeLabel = () => { const bounds=periodBounds(),format=new Intl.DateTimeFormat(data.settings.locale,{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}); return `${format.format(new Date(`${bounds.from}T12:00:00Z`))} – ${format.format(new Date(`${bounds.to}T12:00:00Z`))}`; };
const toast = (message) => { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2400); };
const download = (name, content, type = 'application/json') => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); URL.revokeObjectURL(link.href); };
const empty = (label) => `<div class="empty"><div class="avatar" style="margin:auto">＋</div><p>No ${esc(label)} yet.<br><span class="small">Add one to begin tracking.</span></p></div>`;
const progress = (value, status = '') => `<div class="bar ${status}"><span style="width:${Math.min(100, Math.max(0, Number(value)))}%"></span></div>`;
const compare = (left,right) => typeof left === 'bigint' || typeof right === 'bigint' ? (BigInt(left||0) < BigInt(right||0) ? -1 : BigInt(left||0) > BigInt(right||0) ? 1 : 0) : String(left??'').localeCompare(String(right??''),data.settings.locale,{numeric:true,sensitivity:'base'});
const sorted = (items,page,values={}) => { const state=sortState[page]; return items.slice().sort((a,b)=>(state.direction==='asc'?1:-1)*compare(values[state.key]?.(a) ?? a[state.key],values[state.key]?.(b) ?? b[state.key])); };
const sortButton = (page,key,label) => { const state=sortState[page],active=state.key===key; return `<button class="sort-button ${active?'active':''}" data-sort-page="${page}" data-sort-key="${key}">${esc(label)} <span aria-hidden="true">${active?(state.direction==='asc'?'↑':'↓'):'↕'}</span></button>`; };
const sortSelect = (page,options) => `<label class="sort-select">Sort by <select data-list-sort="${page}">${options.map(([value,label])=>`<option value="${value}" ${sortState[page].key===value?'selected':''}>${esc(label)}</option>`).join('')}</select></label><button class="button icon-button sort-direction" data-list-direction="${page}" aria-label="Reverse sort order">${sortState[page].direction==='asc'?'↑':'↓'}</button>`;
const card = (body, cls = '') => `<section class="card ${cls}">${body}</section>`;
const field = (label, name, type = 'text', value = '', options = []) => `<div class="field"><label for="f-${name}">${esc(label)}</label>${type === 'select' ? `<select id="f-${name}" name="${name}" required>${options.map(([v,l]) => `<option value="${esc(v)}" ${String(v) === String(value) ? 'selected' : ''}>${esc(l)}</option>`).join('')}</select>` : `<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${type === 'number' ? 'step="0.01"' : ''} required>`}</div>`;
const addTransactionMenu = () => `<details class="action-menu"><summary class="button primary">＋ Add transaction <span aria-hidden="true">⌄</span></summary><div class="action-menu-popover" role="menu"><button type="button" data-add="transactions" role="menuitem"><strong>Manual entry</strong><span>Enter transaction details</span></button><button type="button" data-action="sms-import" role="menuitem"><strong>Banking SMS</strong><span>Paste and review a bank message</span></button></div></details>`;

function applyTheme() {
  const setting = data.settings.theme;
  const dark = setting === 'dark' || (setting === 'system' && matchMedia('(prefers-color-scheme: dark)').matches);
  document.documentElement.dataset.theme = dark ? 'dark' : 'light';
}
function shell(page) {
  const nav = routes.concat(data.settings.aiEnabled ? [['assistant','AI Assistant','✦']] : []);
  app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><img class="brand-mark" src="./assets/quiet-ledger-icon.svg" alt="">Quiet Ledger</div><nav class="nav" aria-label="Primary">${nav.map(([key,label,icon]) => `<a href="#/${key}" class="${page === key ? 'active' : ''}"><span class="nav-icon">${icon}</span>${label}</a>`).join('')}</nav></aside><main class="content" id="main"><header class="topbar"><div><p class="eyebrow">${new Intl.DateTimeFormat(data.settings.locale, { weekday:'long', month:'long', day:'numeric' }).format(new Date())}</p><h1>${esc(title(page))}</h1></div><div class="actions"><div class="period-picker" aria-label="Reporting period"><button class="button icon-button" data-action="previous-month" aria-label="Previous month">‹</button><label class="month-control"><span>${esc(periodLabel())}</span><input id="period-month" type="month" value="${selectedMonth}" aria-label="Reporting month"></label><button class="button icon-button" data-action="next-month" aria-label="Next month">›</button></div>${addTransactionMenu()}</div></header><div class="period-context"><span class="badge">Viewing ${esc(periodRangeLabel())}</span>${selectedMonth !== new Date().toISOString().slice(0,7) ? '<button class="button small" data-action="current-month">Return to current month</button>' : ''}</div><div id="page">${renderPage(page)}</div></main><nav class="mobile-nav" aria-label="Mobile">${[['overview','⌂'],['transactions','⇄'],['budget','◫'],['accounts','▣'],['settings','⚙']].map(([key,icon]) => `<a href="#/${key}" class="${page === key ? 'active' : ''}"><span>${icon}</span>${title(key)}</a>`).join('')}</nav></div>`;
}
function summaryMetrics() {
  const cf = cashFlow(periodTransactions()); const worth = netWorth(data.accounts, data.settings.rates);
  const assets = data.accounts.filter((a) => a.group === 'asset' && a.includeNetWorth).reduce((s,a) => s + money(a.balance), 0n);
  const debt = data.accounts.filter((a) => a.group === 'liability' && a.includeNetWorth).reduce((s,a) => s + money(a.balance), 0n);
  const investments = data.holdings.reduce((s,h) => s + investmentGain(h.quantity,h.averageCost,h.currentPrice).value, 0n);
  return { 'net-worth':['Net Worth',worth], cash:['Cash & Bank',assets], investments:['Investments',investments], debt:['Total Debt',debt], income:['Monthly Income',cf.income], expenses:['Monthly Expenses',cf.expenses], surplus:['Monthly Surplus',cf.income-cf.expenses], 'savings-rate':['Savings Rate',savingsRateMinor(cf),true] };
}
const savingsRateMinor = (cf) => cf.income ? ratio(cf.income - cf.expenses, cf.income) : 0n;
function overview() {
  const metrics = summaryMetrics(); const widgets = data.widgets.length ? data.widgets : Object.keys(metrics);
  const cf = cashFlow(periodTransactions()); const total = cf.expenses;
  const spending = data.categories.filter((c) => c.type === 'expense').map((c) => ({ ...c, spent: periodTransactions().filter((t) => t.categoryId === c.id && t.type === 'expense').reduce((s,t) => s + money(t.amount),0n) })).filter((c) => c.spent > 0n);
  const attention = [
    ...data.bills.filter((b) => !b.paid).map((b) => `${b.name} is due ${b.dueDate}`),
    ...data.transactions.filter((t) => !t.categoryId && t.type !== 'transfer').map((t) => `${t.description} needs a category`),
    ...data.accounts.filter((a) => money(a.balance) < 0n).map((a) => `${a.name} has a negative balance`)
  ];
  return `<div class="grid summary-grid">${widgets.map((key) => { const item = metrics[key]; if (!item) return ''; return card(`<span class="metric-label">${item[0]}</span><div class="metric"><strong>${item[2] ? pct(item[1]) : fmt(item[1])}</strong><span class="trend">↑ 4.2%</span></div><svg class="spark" viewBox="0 0 100 30" preserveAspectRatio="none" aria-hidden="true"><polyline points="0,25 14,20 28,22 42,13 56,16 70,8 84,11 100,3"/></svg>`); }).join('')}</div>
  <div class="grid two-col">${card(`<div class="section-head"><div><h2>Cash flow</h2><span class="small muted">Current period</span></div><span class="badge healthy">${pct(savingsRateMinor(cf))} retained</span></div><div class="grid" style="grid-template-columns:150px 1fr;align-items:center"><div class="donut"></div><div><div class="bar-row"><span>Income</span>${progress(100)}<strong>${fmt(cf.income)}</strong></div><div class="bar-row"><span>Expenses</span>${progress(Number(ratio(cf.expenses,cf.income))/100,'warning')}<strong>${fmt(cf.expenses)}</strong></div><div class="bar-row"><span>Remaining</span>${progress(Number(ratio(cf.income-cf.expenses,cf.income))/100)}<strong>${fmt(cf.income-cf.expenses)}</strong></div></div></div>`)}
  ${card(`<div class="section-head"><h2>Attention required</h2><span class="badge ${attention.length ? 'warning' : 'healthy'}">${attention.length}</span></div>${attention.length ? `<div class="list">${attention.slice(0,5).map((text) => `<div class="list-item"><span class="avatar">!</span><div><div class="item-title">${esc(text)}</div><div class="item-meta">Review suggested</div></div><span>›</span></div>`).join('')}</div>` : `<p class="muted">Everything looks settled.</p>`}`)}</div>
  <div class="grid two-col">${card(`<div class="section-head"><h2>Spending by category</h2><a class="small muted" href="#/reports">View report</a></div>${spending.length ? spending.map((c) => `<div class="bar-row"><span>${c.icon} ${esc(c.name)}</span>${progress(Number(ratio(c.spent,total))/100)}<strong>${fmt(c.spent)}</strong></div>`).join('') : empty('spending')}`)}${card(`<div class="section-head"><h2>Budget progress</h2><a class="small muted" href="#/budget">Manage</a></div>${budgetRows(true)}`)}</div>
  <div class="grid two-col">${card(`<div class="section-head"><h2>Goals</h2><a class="small muted" href="#/goals">See all</a></div>${goalCards(true)}`)}${card(`<div class="section-head"><h2>Upcoming bills</h2><a class="small muted" href="#/bills">See all</a></div>${billList(true)}`)}</div>`;
}
function transactionTable(items) { const rows=sorted(items,'transactions',{description:(t)=>t.merchant||t.description,account:(t)=>get('accounts',t.accountId)?.name,category:(t)=>get('categories',t.categoryId)?.name,amount:(t)=>money(t.amount)}); return rows.length ? `<div class="table-wrap"><table><thead><tr><th>${sortButton('transactions','date','Date')}</th><th>${sortButton('transactions','description','Description')}</th><th>${sortButton('transactions','account','Account')}</th><th>${sortButton('transactions','category','Category')}</th><th>${sortButton('transactions','status','Status')}</th><th>${sortButton('transactions','amount','Amount')}</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody>${rows.map((t) => `<tr><td>${esc(t.date)}</td><td><strong>${esc(t.merchant || t.description)}</strong><div class="item-meta">${esc(t.description)}</div></td><td>${esc(get('accounts',t.accountId)?.name || '—')}</td><td>${esc(get('categories',t.categoryId)?.name || 'Uncategorized')}</td><td><span class="badge">${esc(t.status)}</span></td><td class="amount ${t.type}">${t.type === 'expense' ? '−' : t.type === 'transfer' ? '' : '+'}${amt(t.amount,t.currency)}</td><td><button class="button small" data-edit="transactions" data-id="${esc(t.id)}" aria-label="Edit ${esc(t.merchant || t.description)} transaction">Edit</button></td></tr>`).join('')}</tbody></table></div>` : empty('transactions'); }
function accounts() { const groups = ['asset','liability']; return `<div class="toolbar"><button class="button primary" data-add="accounts">＋ Add account</button>${sortSelect('accounts',[['name','Name'],['institution','Institution'],['balance','Balance'],['type','Type']])}</div>${groups.map((group) => {const items=sorted(data.accounts.filter((a)=>a.group===group&&!a.archived),'accounts',{balance:(a)=>money(a.balance)});return card(`<div class="section-head"><h2>${group === 'asset' ? 'Assets' : 'Liabilities'}</h2><strong>${fmt(items.reduce((s,a)=>s+money(a.balance),0n))}</strong></div>${items.length ? `<div class="list">${items.map((a)=>`<div class="list-item"><span class="avatar" style="color:${esc(a.color)}">▣</span><div><div class="item-title">${esc(a.name)}</div><div class="item-meta">${esc(a.institution)} · ${esc(a.type)} · ${esc(a.mask)}</div></div><div><div class="amount">${amt(a.balance,a.currency)}</div><button class="button small" data-edit="accounts" data-id="${a.id}">Edit</button></div></div>`).join('')}</div>` : empty(group+' accounts')}`);}).join('<br>')}`; }
function transactionsPage() { const filtered = periodTransactions().filter((t) => [t.description,t.merchant,get('accounts',t.accountId)?.name,get('categories',t.categoryId)?.name].some((v)=>String(v||'').toLowerCase().includes(search.toLowerCase()))); return `<div class="toolbar"><input id="search" value="${esc(search)}" placeholder="Search ${esc(periodLabel())} transactions…" aria-label="Search transactions">${addTransactionMenu()}<button class="button" data-action="csv-export">Export CSV</button><label class="button">Import CSV<input type="file" id="csv-import" accept=".csv,text/csv" hidden></label></div>${card(transactionTable(filtered))}`; }
function budgetRows(compact=false) { const budgets=data.budgets.filter((budget)=>budget.period===selectedMonth); if (!budgets.length) return empty(`budgets for ${periodLabel()}`); return budgets.slice(0,compact?4:999).map((b) => { const spent=periodTransactions().filter((t)=>t.categoryId===b.categoryId&&t.type==='expense').reduce((s,t)=>s+money(t.amount),0n); const p=budgetProgress(b.amount,decimal(spent),b.warning); return `<div class="bar-row"><span>${esc(get('categories',b.categoryId)?.name||'Category')}</span><div>${progress(Number(p.used)/100,p.status)}<div class="item-meta">${fmt(spent)} of ${amt(b.amount)} · ${fmt(p.remaining)} remaining</div></div><div class="actions"><span class="badge ${p.status}">${pct(p.used)}</span>${compact?'':`<button class="button small" data-edit="budgets" data-id="${esc(b.id)}" aria-label="Edit ${esc(get('categories',b.categoryId)?.name||'category')} budget">Edit</button>`}</div></div>`; }).join(''); }
function budgetPage() { return `<div class="toolbar"><button class="button primary" data-add="budgets">＋ Add budget</button><button class="button" data-action="copy-budget">Copy previous month</button></div>${card(`<div class="section-head"><div><h2>Monthly plan</h2><span class="small muted">Forecasts update from actual spending</span></div></div>${budgetRows()}`)}`; }
function billList(compact=false) { const bills=sorted(data.bills,'bills',{amount:(b)=>money(b.amount),paid:(b)=>b.paid?1:0}).slice(0,compact?4:999); return bills.length ? `<div class="list">${bills.map((b)=>`<div class="list-item"><span class="avatar">▤</span><div><div class="item-title">${esc(b.name)}</div><div class="item-meta">${esc(b.frequency)} · due ${esc(b.dueDate)} · ${b.autopay?'Auto-pay':'Manual'}</div></div><div><div class="amount">${amt(b.amount,b.currency)}</div><div class="actions"><button class="button small" data-action="pay-bill" data-id="${esc(b.id)}">${b.paid?'Reopen':'Mark paid'}</button>${compact?'':`<button class="button small" data-edit="bills" data-id="${esc(b.id)}" aria-label="Edit ${esc(b.name)} bill">Edit</button>`}</div></div></div>`).join('')}</div>` : empty('bills'); }
function bills() { return `<div class="toolbar"><button class="button primary" data-add="bills">＋ Add bill</button><a class="button" href="#/calendar">Calendar view</a>${sortSelect('bills',[['dueDate','Due date'],['name','Name'],['amount','Amount'],['paid','Payment status']])}</div>${card(billList())}`; }
function goalCards(compact=false) { const priorities={high:1,medium:2,low:3}; const goals=sorted(data.goals.filter((g)=>!g.archived),'goals',{priority:(g)=>priorities[g.priority]||4,progress:(g)=>goalProjection(g.current,g.target,g.monthly).completion}).slice(0,compact?3:999); return goals.length ? goals.map((g)=>{const p=goalProjection(g.current,g.target,g.monthly); return `<div class="list-item"><span class="avatar" style="color:${esc(g.color)}">${esc(g.icon)}</span><div><div class="item-title">${esc(g.name)}</div><div class="item-meta">${amt(g.current)} saved · ${p.months===null?'Contribution needed':`${p.months} months estimated`}</div>${progress(Number(p.completion)/100)}</div><strong>${pct(p.completion)}</strong></div>`;}).join('') : empty('goals'); }
function goals() { return `<div class="toolbar"><button class="button primary" data-add="goals">＋ Add goal</button>${sortSelect('goals',[['priority','Priority'],['name','Name'],['targetDate','Target date'],['progress','Progress']])}</div>${card(goalCards())}`; }
function investments() { let holdings=data.holdings.map((h)=>({...h,...investmentGain(h.quantity,h.averageCost,h.currentPrice)})); const value=holdings.reduce((s,h)=>s+h.value,0n),gain=holdings.reduce((s,h)=>s+h.gain,0n); holdings=sorted(holdings,'investments',{quantity:(h)=>money(h.quantity),currentPrice:(h)=>money(h.currentPrice),value:(h)=>h.value,gain:(h)=>h.gain}); return `<div class="grid summary-grid">${card(`<span class="metric-label">Portfolio value</span><div class="metric"><strong>${fmt(value)}</strong></div>`)}${card(`<span class="metric-label">Total gain / loss</span><div class="metric"><strong class="${gain<0n?'expense':'income'}">${fmt(gain)}</strong></div>`)}${card(`<span class="metric-label">Dividend income</span><div class="metric"><strong>${fmt(data.holdings.reduce((s,h)=>s+money(h.dividends||'0'),0n))}</strong></div>`)}</div><br><div class="toolbar"><button class="button primary" data-add="holdings">＋ Add holding</button></div>${card(holdings.length?`<div class="table-wrap"><table><thead><tr><th>${sortButton('investments','name','Holding')}</th><th>${sortButton('investments','assetClass','Class')}</th><th>${sortButton('investments','quantity','Quantity')}</th><th>${sortButton('investments','currentPrice','Price')}</th><th>${sortButton('investments','value','Value')}</th><th>${sortButton('investments','gain','Gain')}</th></tr></thead><tbody>${holdings.map(h=>`<tr><td><strong>${esc(h.name)}</strong><div class="item-meta">${esc(h.symbol)}</div></td><td>${esc(h.assetClass)}</td><td>${esc(h.quantity)}</td><td>${amt(h.currentPrice,h.currency)}</td><td>${fmt(h.value,h.currency)}</td><td class="${h.gain<0n?'expense':'income'}">${fmt(h.gain,h.currency)}</td></tr>`).join('')}</tbody></table></div>`:empty('holdings'))}`; }
function netWorthPage() { const worth=netWorth(data.accounts,data.settings.rates); return `<div class="grid summary-grid">${card(`<span class="metric-label">Current net worth</span><div class="metric"><strong>${fmt(worth)}</strong><span class="trend">↑ 4.2%</span></div>`)}${card(`<span class="metric-label">Included accounts</span><div class="metric"><strong>${data.accounts.filter(a=>a.includeNetWorth).length}</strong></div>`)}</div><br>${card(`<div class="section-head"><h2>Account contribution</h2><span class="small muted">Reporting currency: ${esc(data.settings.primaryCurrency)}</span></div>${data.accounts.filter(a=>a.includeNetWorth).map(a=>`<div class="bar-row"><span>${esc(a.name)}</span>${progress(Math.abs(Number(money(a.balance)*100n/(worth||1n))))}<strong class="${a.group==='liability'?'expense':''}">${a.group==='liability'?'−':''}${amt(a.balance,a.currency)}</strong></div>`).join('')}`)}`; }
function reports() { const transactions=periodTransactions(),cf=cashFlow(transactions); const categoryRows=data.categories.map(c=>({name:c.name,total:transactions.filter(t=>t.categoryId===c.id&&t.type==='expense').reduce((s,t)=>s+money(t.amount),0n)})).filter(c=>c.total).sort((a,b)=>compare(b.total,a.total)); return `<div class="toolbar"><button class="button" onclick="print()">Print</button><button class="button" data-action="csv-export">Export CSV</button></div><div class="grid summary-grid">${card(`<span class="metric-label">Income</span><div class="metric"><strong>${fmt(cf.income)}</strong></div>`)}${card(`<span class="metric-label">Expenses</span><div class="metric"><strong>${fmt(cf.expenses)}</strong></div>`)}${card(`<span class="metric-label">Savings rate</span><div class="metric"><strong>${pct(savingsRateMinor(cf))}</strong></div>`)}</div><br>${card(`<div class="section-head"><h2>Expense report</h2><span class="small muted">Highest spending first · ${esc(periodLabel())}</span></div>${categoryRows.length?categoryRows.map(c=>`<div class="bar-row"><span>${esc(c.name)}</span>${progress(Number(ratio(c.total,cf.expenses))/100)}<strong>${fmt(c.total)}</strong></div>`).join(''):empty('report data')}`)}`; }
function calendar() { const [year,monthNumber]=selectedMonth.split('-').map(Number),month=monthNumber-1,first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(); const cells=Array.from({length:first},()=>'<div></div>').concat(Array.from({length:days},(_,i)=>{const day=i+1,events=data.bills.filter(b=>inPeriod(b,'dueDate')&&new Date(`${b.dueDate}T12:00:00`).getDate()===day);return `<div class="day"><strong>${day}</strong>${events.map(e=>`<span class="event">${esc(e.name)} · ${amt(e.amount,e.currency)}</span>`).join('')}</div>`;})); return `<div class="toolbar"><button class="button">Month</button><button class="button">Week</button><button class="button">Agenda</button><button class="button primary" data-add="bills">＋ Event</button></div>${card(`<div class="section-head"><h2>${esc(periodLabel())}</h2></div><div style="overflow:auto"><div class="calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="calendar-head">${d}</div>`).join('')}${cells.join('')}</div></div>`)}`; }
function loans() { const items=sorted(data.loans,'loans',{balance:(l)=>money(l.balance),annualRate:(l)=>money(l.annualRate),monthlyPayment:(l)=>money(l.monthlyPayment)}); return `<div class="toolbar"><button class="button primary" data-add="loans">＋ Add loan</button>${sortSelect('loans',[['name','Name'],['balance','Balance'],['annualRate','Interest rate'],['monthlyPayment','Monthly payment']])}</div>${items.length?items.map(l=>{let result;try{result=amortize({principal:l.balance,annualRate:l.annualRate,monthlyPayment:l.monthlyPayment,extraPayment:l.extraPayment});}catch(e){result={schedule:[],totalInterest:0n};}return card(`<div class="section-head"><div><h2>${esc(l.name)}</h2><span class="small muted">${esc(l.lender)} · ${esc(l.annualRate)}% ${esc(l.interestType)}</span></div><button class="button" data-edit="loans" data-id="${l.id}">Edit</button></div><div class="grid summary-grid"><div><span class="metric-label">Balance</span><p class="amount" style="text-align:left">${amt(l.balance)}</p></div><div><span class="metric-label">Monthly payment</span><p class="amount" style="text-align:left">${amt(l.monthlyPayment)}</p></div><div><span class="metric-label">Payments left</span><p class="amount" style="text-align:left">${result.schedule.length}</p></div><div><span class="metric-label">Projected interest</span><p class="amount expense" style="text-align:left">${fmt(result.totalInterest)}</p></div></div>`);}).join('<br>'):empty('loans')}`; }
function settings() { const s=data.settings; return `<div class="grid two-col">${card(`<div class="section-head"><h2>General</h2></div><form id="settings-form" class="form-grid">${field('Primary currency','primaryCurrency','select',s.primaryCurrency,s.currencies.map(c=>[c,c]))}${field('Locale','locale','text',s.locale)}${field('Theme','theme','select',s.theme,[['system','System'],['light','Light'],['dark','Dark']])}${field('Time zone','timezone','text',s.timezone)}${field('Financial month starts (1–28)','monthStart','number',s.monthStart)}${field('Budget warning %','budgetWarning','number',s.budgetWarning)}<p class="small muted span-2">The selected month is the reporting month. For example, with day 25 selected, August covers July 25 through August 24.</p><div class="field span-2"><label><input type="checkbox" name="aiEnabled" ${s.aiEnabled?'checked':''}> Enable experimental AI Assistant page</label></div><button class="button primary span-2">Save preferences</button></form>`)}${card(`<div class="section-head"><h2>Dashboard</h2></div><p class="small muted">Choose visible cards and drag-free ordering.</p><div class="list">${Object.entries(summaryMetrics()).map(([key,value])=>`<label class="list-item"><input type="checkbox" data-widget="${key}" ${data.widgets.includes(key)?'checked':''}><span>${esc(value[0])}</span><span class="muted">☰</span></label>`).join('')}</div>`)}</div><br><div class="grid two-col">${card(`<div class="section-head"><h2>Categories</h2><button class="button" data-add="categories">＋ Add</button></div>${data.categories.map(c=>`<div class="list-item"><span class="avatar" style="color:${esc(c.color)}">${esc(c.icon)}</span><div><div class="item-title">${esc(c.name)}</div><div class="item-meta">${esc(c.type)}</div></div><button class="button" data-edit="categories" data-id="${c.id}">Edit</button></div>`).join('')}`)}${card(`<div class="section-head"><h2>Data management</h2></div><div class="callout">Backups include private financial data. Store exported files securely.</div><div class="actions" style="margin-top:16px"><button class="button" data-action="backup">Export backup</button><label class="button">Restore<input id="restore" type="file" accept="application/json" hidden></label><button class="button" data-action="demo">Restore demo</button><button class="button danger" data-action="clear">Clear data</button></div>`)}</div>`; }
function assistant() { return card(`<div class="section-head"><h2>AI Assistant</h2><span class="badge">Feature preview</span></div><p class="muted">Ask questions about your financial picture. No financial data is sent anywhere in this local version.</p><div class="callout">Connect a privacy-reviewed AI provider adapter in Settings before enabling live responses.</div><div class="toolbar" style="margin-top:20px"><input placeholder="e.g. Where did my spending increase?" disabled><button class="button primary" disabled>Ask</button></div>`); }
function renderPage(page) { return ({overview,accounts,transactions:transactionsPage,budget:budgetPage,bills,goals,investments,'net-worth':netWorthPage,reports,calendar,loans,settings,assistant}[page] || overview)(); }

const forms = {
  accounts: (x={}) => `${field('Account name','name','text',x.name)}${field('Institution','institution','text',x.institution)}${field('Type','type','select',x.type||'current',[['current','Current'],['savings','Savings'],['cash','Cash'],['credit-card','Credit card'],['fixed-deposit','Fixed deposit'],['investment','Investment'],['loan','Loan'],['mortgage','Mortgage'],['vehicle-loan','Vehicle loan'],['wallet','Digital wallet'],['other-asset','Other asset'],['other-liability','Other liability']])}${field('Group','group','select',x.group||'asset',[['asset','Asset'],['liability','Liability']])}${field('Currency','currency','select',x.currency||data.settings.primaryCurrency,data.settings.currencies.map(c=>[c,c]))}${field('Balance','balance','number',x.balance||'0.00')}${field('Masked number','mask','text',x.mask||'•••• 0000')}${field('Colour','color','color',x.color||'#24745b')}<div class="field span-2"><label><input type="checkbox" name="includeNetWorth" ${x.includeNetWorth!==false?'checked':''}> Include in net worth</label></div>`,
  transactions: (x={}) => `${field('Date','date','date',x.date||`${selectedMonth}-01`)}${field('Description','description','text',x.description)}${field('Merchant','merchant','text',x.merchant)}${field('Amount','amount','number',x.amount||'0.00')}${field('Currency','currency','select',x.currency||data.settings.primaryCurrency,data.settings.currencies.map(c=>[c,c]))}${field('Type','type','select',x.type||'expense',[['income','Income'],['expense','Expense'],['transfer','Transfer'],['refund','Refund']])}${field('Account','accountId','select',x.accountId||'',data.accounts.map(a=>[a.id,a.name]))}${field('Category','categoryId','select',x.categoryId||'',[['','Uncategorized'],...data.categories.map(c=>[c.id,c.name])])}${field('Status','status','select',x.status||'cleared',[['cleared','Cleared'],['pending','Pending'],['reconciled','Reconciled']])}`,
  budgets: (x={}) => `${field('Category','categoryId','select',x.categoryId||'',data.categories.filter(c=>c.type==='expense').map(c=>[c.id,c.name]))}${field('Budget amount','amount','number',x.amount||'0.00')}${field('Period','period','month',x.period||selectedMonth)}${field('Method','method','select',x.method||'standard',[['standard','Non-rollover'],['rollover','Rollover'],['zero-based','Zero-based']])}${field('Warning threshold %','warning','number',x.warning||data.settings.budgetWarning)}`,
  bills: (x={}) => `${field('Bill name','name','text',x.name)}${field('Payee','payee','text',x.payee)}${field('Amount','amount','number',x.amount||'0.00')}${field('Currency','currency','select',x.currency||data.settings.primaryCurrency,data.settings.currencies.map(c=>[c,c]))}${field('Frequency','frequency','select',x.frequency||'monthly',[['weekly','Weekly'],['biweekly','Every two weeks'],['monthly','Monthly'],['bimonthly','Every two months'],['quarterly','Quarterly'],['semiannual','Every six months'],['annual','Annually'],['custom','Custom']])}${field('Due date','dueDate','date',x.dueDate||new Date().toISOString().slice(0,10))}${field('Account','accountId','select',x.accountId||'',data.accounts.map(a=>[a.id,a.name]))}${field('Reminder days','reminder','number',x.reminder||3)}<div class="field"><label><input type="checkbox" name="autopay" ${x.autopay?'checked':''}> Auto-pay</label></div>`,
  goals: (x={}) => `${field('Goal name','name','text',x.name)}${field('Description','description','text',x.description)}${field('Target amount','target','number',x.target||'0.00')}${field('Current saved','current','number',x.current||'0.00')}${field('Monthly contribution','monthly','number',x.monthly||'0.00')}${field('Target date','targetDate','date',x.targetDate||new Date().toISOString().slice(0,10))}${field('Priority','priority','select',x.priority||'medium',[['low','Low'],['medium','Medium'],['high','High']])}${field('Colour','color','color',x.color||'#24745b')}`,
  holdings: (x={}) => `${field('Name','name','text',x.name)}${field('Symbol','symbol','text',x.symbol)}${field('Asset class','assetClass','text',x.assetClass)}${field('Quantity','quantity','number',x.quantity||'0.00')}${field('Average cost','averageCost','number',x.averageCost||'0.00')}${field('Current price','currentPrice','number',x.currentPrice||'0.00')}${field('Currency','currency','select',x.currency||data.settings.primaryCurrency,data.settings.currencies.map(c=>[c,c]))}${field('Dividends','dividends','number',x.dividends||'0.00')}`,
  loans: (x={}) => `${field('Loan name','name','text',x.name)}${field('Lender','lender','text',x.lender)}${field('Original principal','principal','number',x.principal||'0.00')}${field('Current balance','balance','number',x.balance||'0.00')}${field('Annual interest %','annualRate','number',x.annualRate||'0')}${field('Monthly payment','monthlyPayment','number',x.monthlyPayment||'0.00')}${field('Extra payment','extraPayment','number',x.extraPayment||'0.00')}${field('Interest type','interestType','select',x.interestType||'reducing',[['reducing','Reducing balance'],['flat','Flat']])}`,
  categories: (x={}) => `${field('Category name','name','text',x.name)}${field('Type','type','select',x.type||'expense',[['expense','Expense'],['income','Income']])}${field('Icon','icon','text',x.icon||'○')}${field('Colour','color','color',x.color||'#24745b')}${field('SMS matching keywords','smsKeywords','text',Array.isArray(x.smsKeywords)?x.smsKeywords.join(', '):(x.smsKeywords||''))}`
};
function modal(resource,id='',defaults={}) { const existing=id?get(resource,id):defaults; const label=resource[0].toUpperCase()+resource.slice(1,-1); document.body.insertAdjacentHTML('beforeend',`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><section class="modal-card"><div class="section-head"><h2 id="modal-title">${id?'Edit':'Add'} ${esc(label)}</h2><button class="button icon-button" data-close aria-label="Close">×</button></div>${defaults.importSource === 'banking-sms' ? '<div class="callout">Review the parsed details before saving. The SMS was processed locally.</div>' : ''}<form id="entity-form" data-resource="${resource}" data-id="${id}" class="form-grid">${forms[resource](existing)}${defaults.rawSms ? `<input type="hidden" name="rawSms" value="${esc(defaults.rawSms)}"><input type="hidden" name="importSource" value="banking-sms">` : ''}<div class="actions span-2"><button class="button primary" type="submit">Save</button>${id?'<button class="button danger" type="button" data-delete>Delete</button>':''}<button class="button" type="button" data-close>Cancel</button></div></form></section></div>`); document.querySelector('.modal input:not([type="hidden"])')?.focus(); }
async function smsModal() { let clipboard=''; try { clipboard=await navigator.clipboard?.readText() || ''; } catch { clipboard=''; } document.body.insertAdjacentHTML('beforeend',`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="sms-title"><section class="modal-card"><div class="section-head"><div><h2 id="sms-title">Import banking SMS</h2><span class="small muted">Parsed privately in your browser</span></div><button class="button icon-button" data-close aria-label="Close">×</button></div><form id="sms-form"><div class="field"><label for="banking-sms">Online banking message</label><textarea id="banking-sms" name="sms" rows="7" maxlength="2000" placeholder="Paste a debit or credit notification…" required>${esc(clipboard)}</textarea></div><div class="callout" style="margin-top:14px">No message content is sent to a bank or AI service. Verify the amount, account, and category on the next screen.</div><div class="actions" style="margin-top:18px"><button class="button primary" type="submit">Analyze SMS</button><button class="button" type="button" data-close>Cancel</button></div></form></section></div>`); document.querySelector('#banking-sms').focus(); }
function formValues(form) { const values=Object.fromEntries(new FormData(form)); form.querySelectorAll('input[type=checkbox]').forEach(i=>values[i.name]=i.checked); return values; }
function csv() { const header=['date','description','merchant','amount','currency','account','category','type','status']; const quote=v=>`"${String(v??'').replaceAll('"','""')}"`; return [header.join(','),...periodTransactions().map(t=>[t.date,t.description,t.merchant,t.amount,t.currency,get('accounts',t.accountId)?.name,get('categories',t.categoryId)?.name,t.type,t.status].map(quote).join(','))].join('\n'); }
function moveMonth(offset) { const [year,month]=selectedMonth.split('-').map(Number); const next=new Date(Date.UTC(year,month-1+offset,1)); selectedMonth=next.toISOString().slice(0,7); sessionStorage.setItem('harbor-finance-period',selectedMonth); render(); }
function copyPreviousBudget() { const sourcePeriod=reportingMonthOffset(selectedMonth,-1),source=data.budgets.filter((budget)=>budget.period===sourcePeriod); if(!source.length){toast(`No budgets found for ${monthLabel(sourcePeriod)}`);return;} const existing=new Set(data.budgets.filter((budget)=>budget.period===selectedMonth).map((budget)=>budget.categoryId)),copies=source.filter((budget)=>!existing.has(budget.categoryId)).map((budget)=>({...budget,id:`budg-${crypto.randomUUID()}`,period:selectedMonth})); if(!copies.length){toast(`${periodLabel()} already has budgets for every previous category`);return;} data.budgets=[...data.budgets,...copies];repo.save(data);render();toast(`${copies.length} budget${copies.length===1?'':'s'} copied from ${monthLabel(sourcePeriod)}`); }
function render() { data=repo.load(); applyTheme(); shell(route()); }

document.addEventListener('submit',(event)=>{ event.preventDefault(); const form=event.target;
  try { if(form.id==='sms-form'){const parsed=parseBankingSms(new FormData(form).get('sms'),{accounts:data.accounts,categories:data.categories,primaryCurrency:data.settings.primaryCurrency});form.closest('.modal').remove();modal('transactions','',parsed);return;} if(form.id==='entity-form'){const values=formValues(form); ['amount','balance','target','current','monthly','principal','monthlyPayment','extraPayment','averageCost','currentPrice','dividends','quantity'].forEach(k=>{if(k in values) money(values[k]);}); const resource=form.dataset.resource,id=form.dataset.id; if(resource==='accounts') values.archived=false; if(resource==='categories') values.smsKeywords=String(values.smsKeywords||'').split(',').map((value)=>value.trim()).filter(Boolean); if(resource==='bills') values.paid=get(resource,id)?.paid||false; if(resource==='goals'){values.archived=false;values.icon=get(resource,id)?.icon||'◎';values.type=get(resource,id)?.type||'custom';} id?repo.update(resource,id,values):repo.create(resource,values); document.querySelector('.modal').remove(); render(); toast(`${resource.slice(0,-1)} saved`); return;} if(form.id==='settings-form'){const v=formValues(form),monthStart=Number(v.monthStart);financialPeriod(selectedMonth,monthStart);data.settings={...data.settings,...v,monthStart,budgetWarning:Number(v.budgetWarning)};repo.save(data);render();toast('Preferences saved');} } catch(error){toast(error.message);} });
document.addEventListener('click',(event)=>{const target=event.target.closest('[data-action],[data-add],[data-edit],[data-close],[data-delete],[data-sort-page],[data-list-direction]');if(!target)return;
  if(target.dataset.sortPage){const state=sortState[target.dataset.sortPage];state.direction=state.key===target.dataset.sortKey?(state.direction==='asc'?'desc':'asc'):'asc';state.key=target.dataset.sortKey;render();return;} if(target.dataset.listDirection){const state=sortState[target.dataset.listDirection];state.direction=state.direction==='asc'?'desc':'asc';render();return;}
  if(target.dataset.close!==undefined){target.closest('.modal').remove();return;} if(target.dataset.add){target.closest('.action-menu')?.removeAttribute('open');modal(target.dataset.add);return;} if(target.dataset.edit){modal(target.dataset.edit,target.dataset.id);return;} if(target.dataset.delete!==undefined){const form=target.closest('form');if(confirm('Delete this record? This cannot be undone.')){repo.remove(form.dataset.resource,form.dataset.id);target.closest('.modal').remove();render();}return;}
  const action=target.dataset.action;if(action==='previous-month')moveMonth(-1); if(action==='next-month')moveMonth(1); if(action==='current-month'){selectedMonth=new Date().toISOString().slice(0,7);sessionStorage.setItem('harbor-finance-period',selectedMonth);render();} if(action==='sms-import'){target.closest('.action-menu')?.removeAttribute('open');smsModal();} if(action==='pay-bill'){const bill=get('bills',target.dataset.id),paid=!bill.paid;repo.update('bills',bill.id,{paid});render();toast(paid?'Bill marked paid':'Bill reopened');} if(action==='csv-export')download(`transactions-${selectedMonth}.csv`,csv(),'text/csv'); if(action==='backup')download(`quiet-ledger-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2)); if(action==='demo'&&confirm('Replace current data with removable demo data?')){repo.clear(true);render();} if(action==='clear'&&confirm('Delete all local financial data? Export a backup first if needed.')){repo.clear(false);render();} if(action==='copy-budget')copyPreviousBudget();
});
document.addEventListener('click',(event)=>{document.querySelectorAll('.action-menu[open]').forEach((menu)=>{if(!menu.contains(event.target))menu.removeAttribute('open');});});
document.addEventListener('keydown',(event)=>{if(event.key==='Escape')document.querySelectorAll('.action-menu[open]').forEach((menu)=>menu.removeAttribute('open'));});
document.addEventListener('input',(event)=>{if(event.target.id==='search'){search=event.target.value;document.querySelector('#page').innerHTML=transactionsPage();} if(event.target.dataset.widget){const key=event.target.dataset.widget;data.widgets=event.target.checked?[...new Set([...data.widgets,key])]:data.widgets.filter(x=>x!==key);repo.save(data);}});
document.addEventListener('change',async(event)=>{if(event.target.dataset.listSort){sortState[event.target.dataset.listSort].key=event.target.value;render();} if(event.target.id==='period-month'&&/^\d{4}-\d{2}$/.test(event.target.value)){selectedMonth=event.target.value;sessionStorage.setItem('harbor-finance-period',selectedMonth);render();} if(event.target.id==='restore'){try{repo.replace(JSON.parse(await event.target.files[0].text()));render();toast('Backup restored');}catch(error){toast(error.message);}} if(event.target.id==='csv-import'){try{const lines=(await event.target.files[0].text()).trim().split(/\r?\n/);if(lines.length<2)throw new Error('CSV contains no rows');toast('CSV validated. Use backup restore for full-fidelity import.');}catch(error){toast(error.message);}}});
window.addEventListener('hashchange',render); repo.subscribe((next)=>{data=next;}); render();
